apiVersion: v1
name: bedrock-chart
description: A Helm chart for the ACK service controller for Amazon Bedrock (Bedrock)
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/aws-controllers-k8s/bedrock-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/bedrock-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Bedrock Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/bedrock-maintainer
keywords:
  - aws
  - kubernetes
  - bedrock
